### ISSUE TITLE
sendGetStatuses  Dosent work with me

### ISSUE THREAD

**Issue by xzahirx** [mgp25/WhatsAPI-Official#256]
hello,
sendGetStatuses dosent work with me i dont know why 
and this's my code
```javascript
$w = new WhatsProt($username, $identity, $nickname, $debug);
$events = new MyEvents($w);
$events->setEventsToListenFor(array("onGetRequestLastSeen", "onGetStatus", "onGetProfilePicture"));
$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!
$w->sendGetRequestLastSeen("xxx");
$w->sendGetStatuses("xxx@s.whatsapp.net");
$w->sendGetProfilePicture("xxx");
```
sendGetRequestLastSeen is Working
sendGetProfilePicture is working
sendGetStatuses dosent work and give me this error
`Warning: Invalid argument supplied for foreach() in \src\whatsprot.class.php on line 3041`

**Comment by xzahirx** [comment]
no one is answer, :)

**Comment by mgp25** [comment]
@xzahirx i'll try tomorrow

Regards

**Comment by xzahirx** [comment]
ok thank you
i'll wait for u bro

Regards

**Comment by thiagupct** [comment]
@xzahirx it should be ```$w->sendGetStatuses("9876543210");``` not ```$w->sendGetStatuses("9876543210@s.whatsapp.net");``` Have a try.

**Comment by matteocontrini** [comment]
@mgp25 removing the `t` attribute from the request should fix this

**Comment by mgp25** [comment]
Thanks @matteocontrini 

Fixed: https://github.com/mgp25/WhatsAPI-Official/commit/3996d75239df2a47d3168e60de064970f466b6a8

**Comment by deepakdaswani** [comment]
Hi everyone, how are you. I have been researching about this and trying Whatsapi but I'm afraid that removing this "t" parameter does not solve the issue. After doing many tries, GetRequestLastSeen and GetProfilePic work correctly, but SendGetStatuses continues not working even after removing this parameter. Does anyone have the some problem? Thanks to everyone and best regards :)

**Comment by 0xTryCatch** [comment]
Can you post a debug log to show us what is sent and received?

**Comment by deepakdaswani** [comment]
Not able to post a debug log right now in this moment, but it sends the node <iq> with the information of the numbers and it does not receive anything

**Comment by mgp25** [comment]
@deepakdaswani 

```php
$number = "1234567890";
$w->sendGetStatuses($number);
$w->pollMessage();
```

Try it, i just try it and its working.

Regards

**Comment by deepakdaswani** [comment]
In the debug log yesterday I saw no node is received after sending the iq node. Maybe i am missing out something. Do you need to call to pollMessage to receive the node with the information of the status of all the numbers? I thaught that you can handle this binding the function OnGetStatus

**Comment by matteocontrini** [comment]
Incoming nodes are not processed without pollMessage

--
Matteo
Inviato da Windows Phone

----- Messaggio originale -----
Da: "deepakdaswani" <notifications@github.com>
Inviato: ‎12/‎01/‎2015 11:57
A: "mgp25/WhatsAPI-Official" <WhatsAPI-Official@noreply.github.com>
Cc: "Matteo Contrini" <m.contrini@gmail.com>
Oggetto: Re: [WhatsAPI-Official] sendGetStatuses  Dosent work with me (#256)

In the debug log yesterday I saw no node is received after sending the iq node. Maybe i am missing out something. Do you need to call to pollMessage to receive the node with the information of the status of all the numbers? I thaught that you can handle this binding the function OnGetStatus

**Comment by mgp25** [comment]
@deepakdaswani Yes, but maybe you are closing connection to soon, if you add `$w->pollMessage`right after the call, you should receive it.

**Comment by deepakdaswani** [comment]
I did not know that. Thanks to both of you. I will try right now :)

**Comment by deepakdaswani** [comment]
I have just tried and I see I receive a node <ib from="s.whatsapp.net"> <offline count="0"></offline></ib> but nothing happens. I am binding the function onGetStatus like the others but it does not do anything. Maybe I am missing something... 
By the way, maybe I am confused. This GetStatus returns the string with the "Status" of the user's profile or it returns if he/she is online/offline. I want to get the string with the user's status where many users have "Hey there! I am using Whatsapp"...

**Comment by deepakdaswani** [comment]
This is the code and the debug log. It does not seem to work:

print_r($estados);
$w->sendGetStatuses($estados);
$w->pollMessage();


Array
(
    [0] => 33XXXXXXXXX
    [1] => 34XXXXXXXXX
    [2] => 34XXXXXXXXX
)
tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="getstatus-1421066920-1">
tx    <status>
tx      <user jid="33XXXXXXXXX@s.whatsapp.net"></user>
tx      <user jid="34XXXXXXXXX@s.whatsapp.net"></user>
tx      <user jid="34XXXXXXXXX@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

**Comment by mgp25** [comment]
Code:
```php
$w->sendGetStatuses(array("34***", "34***"));

while(1){
    $w->pollMessage();
//
}
```
Output:

```xml
tx  <iq to="s.whatsapp.net" type="get" xmlns="status" id="getstatus-1421075985-2">
tx    <status>
tx      <user jid="34***@s.whatsapp.net"></user>
tx      <user jid="34***@s.whatsapp.net"></user>
tx    </status>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="getstatus-1421075985-2" type="result">
rx    <status>
rx      <user jid="34***@s.whatsapp.net" type="fail" code="401"></user>
rx      <user jid="34***@s.whatsapp.net" t="1412930245">Disponible</user>
rx    </status>
rx  </iq>
```

**Comment by deepakdaswani** [comment]
With the while(1) is finally working... Thanks! I'll need to set a condition to break the while when I successfully get all the status messages. Thanks a lot and sorry for the trouble!
