### ISSUE TITLE
broadcast send message problem

### ISSUE THREAD

**Issue by enzolarosa** [mgp25/WhatsAPI-Official#274]
hello i am trying to send messages broadcast to my contact and that of friends who have entered into their address book contact that I use to send ... I try to send the message from the pc tells me that was successfully sent just not get the message to the recipients ... I synced the contacts of the recipients on the account that I use for sending, but still does not work ...
have any suggestions ??

thanks Vincenzo La Rosa

below the result of the request
```xml
<message to="1420883450@broadcast" type="text" id="broadcast-1420883450-3">
tx    <broadcast>
tx      <to jid="39xxxxxx@s.whatsapp.net"></to>
tx      <to jid="39xxxxxx@s.whatsapp.net"></to>
tx      <to jid="39xxxxx@s.whatsapp.net"></to>
tx      <to jid="39xxxxx@s.whatsapp.net"></to>
tx      <to jid="39xxxx@s.whatsapp.net"></to>
tx      <to jid="39xxxx@s.whatsapp.net"></to>
tx    </broadcast>
tx    <x xmlns="jabber:x:event">
tx      <server></server>
tx    </x>
tx    <body>Ciao messaggio in broadcast mandato dal pc! Prova a rispondere< /body>
tx  </message>
rx  <iq from="s.whatsapp.net" id="sendstatus-1420883450-2" type="result"></iq>

tx  < stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>
```

This is the code that I use for sending
```php
$targets=array(
'39xxx',
'39xxx',
etc...
)
;
$w=  w_connect();
    $w->sendBroadcastMessage($targets, $message);
    $w->pollMessage();
```

**Comment by mgp25** [comment]
Your friends must have your number added in their address book, if not added thet wont receive any message.

Regards

**Comment by enzolarosa** [comment]
were added .. and synchronized properly ... because if I try to do a broadcast with a photo makes properly and smoothly ..
I do not understand what the problem is

**Comment by mgp25** [comment]
Im going to try it in a while and ill tell you if its working or not.

Regards

**Comment by enzolarosa** [comment]
if I send a broadcast with a video or still image or a media everything runs quietly and use the following function

function w_broadcast_img($targets,$file){
    $w=  w_connect();
    $w->sendBroadcastImage($targets, $file);
    $w->pollMessage();
    return 1;
}

but if I send a text message does not get the messages and use the following function

function w_broadcast_mex($targets,$message){
    $w=  w_connect();
    $w->sendBroadcastMessage($targets, $message);
    $w->pollMessage();
    return 1;
}


contacts in their address books in question have the sender .. also because I'm trying everything with my number and that of my team and have all the numbers in memory like any other contact, I can not understand the reason for not working: (

**Comment by morettolss** [comment]
Hi, yust try and works:

this is my code:

> $w = new WhatsProt($username, $identity, $nickname, $debug);
> $w->connect();
> $w->loginWithPassword($password);
> $targets = array("xxxxxx", "xxxxx");
> $message = "test";
> $w->sendBroadcastMessage($targets, $message);
> $w->pollMessage();

Please check the prefix of mobile phone (39 if in Italy, like me)

**Comment by enzolarosa** [comment]
I do not send messages ... but only with text messages with pictures or video or audio broadcast work like a dream :(

**Comment by morettolss** [comment]
It is possible that the problem is with the $message, try put a simple word like "test". Confirm that works.

**Comment by mgp25** [comment]
@enzolarosa @morettolss im going to check it tonight, if anything have changed i'll update it.

Regards

**Comment by mgp25** [comment]
Fixed: 2a8aa676bd836f57f3a9cc76e975f9bdab536837

**Comment by enzolarosa** [comment]
other strange thing
if I write the text and right after I send a picture in broadcast sends the text (but not always)
if you send only the text does not work


@mgp25  I updated last night with the new files but not much has changed (always speaking of broadcast)

**Comment by enzolarosa** [comment]
Having said that I always contact in phonebook

still doesnt work .. and I'm getting stupid ...
Use this code

$to=array('393897953142');
echo "PRIMA";
w_broadcast_mex_img($to,"PRIMO");
echo "SECONDO";
w_broadcast_mex_img($to,"SECONDO","cv_mascotte_group.jpg","SELINO");

the content of the function

function w_broadcast_mex_img($to,$message,$file=NULL,$caption=""){
    $w = w_connect();
    $w->sendBroadcastMessage($to, $message);
    if ($file!=NULL){
        $w->sendBroadcastImage($to, $file,false,0,"",$caption);
    }
    $w->pollMessage();
    return 1;
}

the second broadcast where also send the photo arrives correctly, the first where I send only the text does not come ...
I updated this morning with the fix you've done but still does not work :(

**Comment by mgp25** [comment]
```php
function w_broadcast_mex_img($to,$message,$file=NULL,$caption=""){
    $w = w_connect();
    $w->sendBroadcastMessage($to, $message);
    $w->pollMessage();
    if ($file!=NULL){
        $w->sendBroadcastImage($to, $file,false,0,"",$caption);
    }
    $w->pollMessage();
    return 1;
}
```

**Comment by enzolarosa** [comment]
no still does not get the first message :(

this is the result with debugging active
```xml
PRIMAtx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="393382081860">9{dÓ393382081860¹_ ¾úÁq—ó)°Ìj’Ä±1421059586WhatsApp/2.11.489 Android/4.3 Device/GalaxyS3 MccMnc/222001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>-)å•»Ív=¿ò1+3¨C7a}</challenge>

tx  <response>FPp»]®çDbÐà¥¢°O^q.42¸Y+Í±YcýÛŸK{ù</response>

rx  <success t="1421059587" props="4" kind="free" status="active" creation="1420627297" expiration="1452163297">´6¥ˆI¬Ìšç>@O³O¨öi¤/</success>

tx  <presence name="LRWeb"></presence>

tx  <message to="1421059587@broadcast" type="text" id="broadcast-1421059587-1">
tx    <body>PRIMO</body>
tx    <broadcast>
tx      <to jid="393897953142@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-1" participant="393897953142@s.whatsapp.net" offline="0" t="1421059090"></receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-1" type="read" t="1421059587"></ack>

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-4" participant="393897953142@s.whatsapp.net" offline="0" t="1421059090"></receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-4" type="read" t="1421059587"></ack>

SECONDOtx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="393382081860">ÿ6ÇL393382081860´6¥ˆI¬Ìšç>@O³O¨öi¤/1421059587WhatsApp/2.11.489 Android/4.3 Device/GalaxyS3 MccMnc/222001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>ÈÔ›\ºc±,kbZ¯></challenge>

tx  <response>X}²r™bTI+ù"	‹Ÿr²™<Šìå™UFOS}ô</response>

rx  <success t="1421059587" props="4" kind="free" status="active" creation="1420627297" expiration="1452163297">sƒ@|AÍŒJÆBúÔìB>ª+^È</success>

tx  <presence name="LRWeb"></presence>

tx  <message to="1421059588@broadcast" type="text" id="broadcast-1421059588-1">
tx    <body>SECONDO</body>
tx    <broadcast>
tx      <to jid="393897953142@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-1" participant="393897953142@s.whatsapp.net" retry="1" offline="1" t="1421059090"></receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-1" type="read" t="1421059588"></ack>

tx  <iq id="upload-1421059588-2" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="3ZD+qc7MmUPLXBOF4PU+P7kOBKJIV3WpZ4Op3bN6Qcg=" type="image" size="36762"></media>
tx  </iq>

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-4" participant="393897953142@s.whatsapp.net" offline="0" t="1421059090"></receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-4" type="read" t="1421059588"></ack>

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-1" participant="393897953142@s.whatsapp.net" offline="0" type="read" t="1421059101">
rx    <list>
rx      <item id="broadcast-1421059088-4"></item>
rx    </list>
rx  </receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-1" type="read" t="1421059588"></ack>

rx  <ib from="s.whatsapp.net">
rx    <offline count="3"></offline>
rx  </ib>

rx  <presence from="393382081860@s.whatsapp.net"></presence>

rx  <ack from="1421059588@broadcast" id="broadcast-1421059588-1" class="message" count="1" t="1421059588"></ack>

rx  <iq from="s.whatsapp.net" id="upload-1421059588-2" type="result">
rx    <duplicate url="https://mmi619.whatsapp.net/d/AmHnLm4FSjMEQhq8UsQX3JOgmQj7EhB7KXDr_c7bOzv6.jpg" size="36762" mimetype="image/jpeg" filehash="3ZD+qc7MmUPLXBOF4PU+P7kOBKJIV3WpZ4Op3bN6Qcg=" type="image" width="350" height="350"></duplicate>
rx  </iq>

tx  <message to="1421059588@broadcast" type="media" id="broadcast-1421059588-4">
tx    <media type="image" url="https://mmi619.whatsapp.net/d/AmHnLm4FSjMEQhq8UsQX3JOgmQj7EhB7KXDr_c7bOzv6.jpg" encoding="raw" file="AmHnLm4FSjMEQhq8UsQX3JOgmQj7EhB7KXDr_c7bOzv6.jpg" size="36762" caption="SELINO"> 3287 byte data</media>
tx    <broadcast>
tx      <to jid="393897953142@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

rx  <ack from="1421059588@broadcast" id="broadcast-1421059588-4" class="message" count="1" t="1421059588"></ack>
```

**Comment by mgp25** [comment]
@enzolarosa As you can see here:

```xml

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-1" participant="***@s.whatsapp.net" offline="0" t="1421059090"></receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-1" type="read" t="1421059587"></ack>

rx  <receipt from="1421059088@broadcast" id="broadcast-1421059088-4" participant="***@s.whatsapp.net" offline="0" t="1421059090"></receipt>

tx  <ack to="1421059088@broadcast" id="broadcast-1421059088-4" type="read" t="1421059587"></ack>
```

You are getting correctly the message and you are getting the read receipt, so you have receive it correctly and viewed it.

**Comment by enzolarosa** [comment]
But the message I get on the phone .. depends on my phone at this point?

The "PRIMO" does not come ... the message "SECONDO" with the photo arrives properly

**Comment by mgp25** [comment]
You should receive it, as i see in the logs you should receive this:

```
(1º msg) - PRIMO

(2º msg) - SECONDO

(3º msg) - [IMAGE]
```

**Comment by enzolarosa** [comment]
I receive only

(2º msg) - SECONDO

(3º msg) - [IMAGE]

and do not understand why ...
since the second time has only added a picture and just :(

**Comment by mgp25** [comment]
@enzolarosa try without reconnecting. In the same session

**Comment by enzolarosa** [comment]
written so

'''php
$w = w_connect();
    $w->sendBroadcastMessage($to, "PRIMO");
    $w->pollMessage();
    $w->sendBroadcastMessage($to, "SECONDO");
    $w->pollMessage();
$w->sendBroadcastImage($to, "cv_mascotte_group.jpg");

$w->pollMessage();
'''

arrive in the following order

SECONDO

FIRST

IMAGE

**Comment by mgp25** [comment]
@enzolarosa 

```php
$w = w_connect();
    $w->sendBroadcastMessage($to, "PRIMO");
    $w->pollMessage();
    sleep(1);
    $w->sendBroadcastMessage($to, "SECONDO");
    $w->pollMessage();
    sleep(1);
   $w->sendBroadcastImage($to, "cv_mascotte_group.jpg");
   $w->pollMessage();
```

**Comment by enzolarosa** [comment]
now it seems to work ...

Now I try to use the function by adding the break

**Comment by enzolarosa** [comment]
now it works ...
because without the break did not work?

what was the problem?

**Comment by morettolss** [comment]
It's not human send 3 message at the same time :-)
