### ISSUE TITLE
Can only send messages if the conversation is deleted.

### ISSUE THREAD

**Issue by Derpanel** [mgp25/WhatsAPI-Official#625]
When I send a message for the first time - i.e. when its the first conversation - it is sent and received without issues.
However, sending another message to the same contact conversation doesn't work.
Only if he deletes the conversation on his phone I am able to message him again - but again, only once until he deletes conversation.

script:
```php
require_once('../src/whatsprot.class.php');

$debug = true;

$username = '972542230174';
$nickname = 'Testing Phone';
$password = '**';
$target = '972546615655';

$w = new WhatsProt($username, $nickname, $debug);

$w->connect();

$w->loginWithPassword($password);

$w->sendMessage($target, 'Testing 123');
```

debug:
```php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="972542230174">‡ø	9725422301740ã­^òêÂä6[pÍ²ˆµ1429701084</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>1TW›|[žÚŽ<äÐâk‚Í¾½</challenge>

tx  <response>LCqÖå®Æ>zJâšŸ9Òþæï*æh}"‚Mƒu©s</response>

rx  <success t="1429701084" props="4" kind="free" status="active" creation="1429517330" expiration="1461053330">1üb dÒÐóÆs…ˆþk‡ÏDÕå</success>

tx  <presence name="Testing Phone"></presence>

tx  <message to="972546615655@s.whatsapp.net" type="text" id="1" t="1429701084">
tx    <body>Testing 123</body>
tx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="972542230174@s.whatsapp.net"></presence>

rx  <presence from="972546615655@s.whatsapp.net"></presence>

rx  <ack from="972546615655@s.whatsapp.net" id="1" class="message" t="1429701084"></ack>

rx  <receipt from="972546615655@s.whatsapp.net" id="1" t="1429701084"></receipt>

tx  <ack to="972546615655@s.whatsapp.net" id="1" type="read" t="1429701084"></ack>
```

**Comment by mgp25** [comment]
@Derpanel can you try latest commit?

Regards

**Comment by mgp25** [comment]
@Derpanel fixed with latest commit :)

**Comment by Derpanel** [comment]
Tried the latest commit, still can't receive the message, same problem as before.
I even tried sending from a different number.

Script:
```php
<?php
require_once("../src/whatsprot.class.php");

$username = "972504837384";
$nickname = "Testing Phone";
$password = 'WE3wk6hTablxJs79HWQ84g7dX50=';
$target = '972546615655';

$debug = true;

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect();

$w->loginWithPassword($password);

$w->sendMessage($target, 'Hello world');
```

Debug:
```php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="972504837384">,TЭb972504837384p<ЫхзЩ|^=JР2а^Ыс ╖д>1429719907</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>тЕ╦`▀еЩэ5чc\ ╙Зоt</challenge>

tx  <response>т╦Ю1^·ЇLД6╓Г\ёhiЭ╠w▐ЩЛ@·w▄@ЯЦ.C</response>

rx  <success t="1429716209" props="4" kind="free" status="active" creation="1429715676" expiration="1461251676">DI·▀#▐EпOае_╬P╬}Pт</success>

tx  <presence name="Testing Phone"></presence>

tx  <message to="972546615655@s.whatsapp.net" type="text" id="1" t="1429719907">
tx    <body>Hello world</body>
tx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="972504837384@s.whatsapp.net"></presence>

rx  <presence from="972546615655@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <ack from="972546615655@s.whatsapp.net" id="1" class="message" t="1429716209"></ack>

rx  <receipt from="972546615655@s.whatsapp.net" id="1" t="1429716212"></receipt>

tx  <ack to="972546615655@s.whatsapp.net" id="1" type="read" t="1429719910"></ack>
```

**Comment by mgp25** [comment]
@Derpanel any error during execution?

**Comment by Derpanel** [comment]
No errors or notices, the debug info is the only output I get.

**Comment by mgp25** [comment]
@Derpanel send me an email please

**Comment by Derpanel** [comment]
Sent to me@mgp25.com

**Comment by matteocontrini** [comment]
^^^ reference to a similar issue on node-whatsapi ^^^
Has this been solved for you, @Derpanel?

**Comment by mgp25** [comment]
@matteocontrini fixed in latest commits

**Comment by Derpanel** [comment]
@matteocontrini Yes, it was fixed in latest commit.
